version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"  # Edge port for all services
      - "4572:4572"  # Specific port for S3 (deprecated but sometimes used)
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=us-east-1
      - DEBUG=1
    volumes:
      - "./localstack:/var/lib/localstack"
